apiVersion: v1
kind: Pod
metadata:
  name: menashe
spec:
  containers:
  - name: animals
    image: supergiantkir/animals:bear
    volumeMounts:
    - name: app-storage
      mountPath: /tmp/pod1
  - name: music
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: app-storage
      mountPath: /tmp/pod2
  volumes:
  - name: app-storage
    hostPath:
      path: "/tmp/files"
